# _config.yml

title: “Travis B — Cloud-Native Architect”
description: “Cloud-native architect specializing in Docker, Kubernetes, microservices and AI-enhanced GitOps.”
theme: pages-themes/hacker@v0.2.0
