# _config.yml
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: “Travis B — Cloud-Native Architect”
description: “Cloud-native architect specializing in Docker, Kubernetes, microservices and AI-enhanced GitOps.”
